const bank={Aptitude:[["If 20% of a number is 40, what is the number?",["120","180","200","240"],2],["A train travels 60 km in 45 minutes. Its speed is?",["60 km/h","70 km/h","80 km/h","90 km/h"],2],["A product marked ₹800 gets a 15% discount. Selling price?",["₹650","₹680","₹700","₹720"],1],["Average of 10,20,30,40 is:",["20","25","30","35"],1]],DSA:[["Which data structure follows LIFO?",["Queue","Stack","Tree","Graph"],1],["Binary search has average time complexity:",["O(n)","O(log n)","O(n log n)","O(1)"],1],["Which traversal uses a queue?",["DFS","BFS","Inorder","Postorder"],1],["Best-case insertion at the beginning of a linked list is:",["O(1)","O(log n)","O(n)","O(n log n)"],0]],DBMS:[["Which command removes all rows but keeps the table?",["DROP","DELETE","TRUNCATE","REMOVE"],2],["A primary key must be:",["Nullable","Unique","Duplicated","Optional"],1],["Which normal form removes partial dependency?",["1NF","2NF","3NF","BCNF"],1],["Which SQL clause filters grouped records?",["WHERE","ORDER BY","HAVING","GROUP BY"],2]],OOP:[["Which concept allows one interface with different implementations?",["Encapsulation","Inheritance","Polymorphism","Compilation"],2],["Which Java keyword refers to the current object?",["self","this","current","object"],1],["Which supports multiple behaviors through the same method name?",["Overloading","Casting","Packaging","Parsing"],0],["A class acquiring properties from another class is:",["Abstraction","Inheritance","Compilation","Aggregation"],1]]};
let topic="",index=0,done=false,stats=JSON.parse(localStorage.getItem("coachStats")||'{"solved":0,"correct":0,"by":{}}');stats.by=stats.by||{};
const $=id=>document.getElementById(id);
function update(){const acc=stats.solved?Math.round(stats.correct/stats.solved*100):0;const readiness=Math.min(100,Math.round(25+acc*.5+Math.min(25,stats.solved*2)));$("solvedHero").textContent=stats.solved;$("accuracyHero").textContent=acc+"%";$("readiness").textContent=readiness+"%";$("heroMeter").style.width=Math.min(100,stats.solved*5)+"%";const vals={Aptitude:0,DSA:0,DBMS:0,OOP:0};Object.keys(vals).forEach(k=>{const s=stats.by[k]||{s:0,c:0};vals[k]=s.s?Math.round(s.c/s.s*100):0});$("skillA").style.width=vals.Aptitude+"%";$("skillD").style.width=vals.DSA+"%";$("skillB").style.width=vals.DBMS+"%";$("skillO").style.width=vals.OOP+"%";localStorage.setItem("coachStats",JSON.stringify(stats))}
function load(){done=false;$("feedback").textContent="";$("next").hidden=true;const q=bank[topic][index%bank[topic].length];$("tag").textContent=topic.toUpperCase();$("qcount").textContent="Question "+((index%bank[topic].length)+1)+" / "+bank[topic].length;$("question").textContent=q[0];$("options").innerHTML=q[1].map((x,i)=>'<button class="option" data-i="'+i+'">'+String.fromCharCode(65+i)+'. '+x+'</button>').join("");document.querySelectorAll(".option").forEach(b=>b.onclick=()=>answer(+b.dataset.i,q[2]))}
function answer(choice,correct){if(done)return;done=true;stats.solved++;stats.by[topic]=stats.by[topic]||{s:0,c:0};stats.by[topic].s++;document.querySelectorAll(".option").forEach((b,i)=>{if(i===correct)b.classList.add("correct");if(i===choice&&i!==correct)b.classList.add("wrong")});if(choice===correct){stats.correct++;stats.by[topic].c++;$("feedback").textContent="✓ Correct — strong answer."}else $("feedback").textContent="✕ Not quite — review this concept and try again.";const s=stats.by[topic];$("insightTitle").textContent=topic+" progress";$("insight").textContent=(Math.round(s.c/s.s*100))+"% accuracy in "+topic+". Keep practicing to build consistency.";$("next").hidden=false;update()}
document.querySelectorAll(".topics button").forEach(b=>b.onclick=()=>{topic=b.dataset.topic;index=0;document.querySelectorAll(".topics button").forEach(x=>x.classList.remove("active"));b.classList.add("active");load()});
$("next").onclick=()=>{index++;load()};
function reply(v){const s=v.toLowerCase();if(s.includes("java"))return"Java question: What is the difference between method overloading and method overriding? Answer using concept → example → result.";if(s.includes("dsa"))return"DSA question: Compare an array and a linked list. When would you choose each? Explain your reasoning.";if(s.includes("hr"))return"HR question: Tell me about yourself in 60 seconds. Focus on your skills, projects, strengths and career goal.";if(v.length>30)return"Good attempt. Improve it with this structure: define the concept → give a practical example → mention the result or trade-off.";return"Choose Java, DSA or HR above and I’ll give you a placement-style question."}
function add(t,c){const p=document.createElement("p");p.className="bubble "+c;p.textContent=t;$("chat").appendChild(p);$("chat").scrollTop=$("chat").scrollHeight}
$("form").onsubmit=e=>{e.preventDefault();const v=$("input").value.trim();if(!v)return;add(v,"user");$("input").value="";setTimeout(()=>add(reply(v),"bot"),180)};
document.querySelectorAll(".prompts button").forEach(b=>b.onclick=()=>{add(b.dataset.p+" interview practice","user");setTimeout(()=>add(reply(b.dataset.p),"bot"),180)});
update();